MODEL:
  ATSS:
    NUM_CLASSES: 8
  FCOS:
    NUM_CLASSES: 8
  ROI_BOX_HEAD:
    NUM_CLASSES: 8
  DYHEAD:
    NUM_CLASSES: 8
DATASETS:
  TEST: ("refcocog_test", )
  FLICKR_GT_TYPE: "separate"

INPUT:
  MIN_SIZE_TRAIN: 800
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
  ASPECT_RATIO_GROUPING: False
SOLVER:
  WARMUP_ITERS: 0
  MAX_EPOCH: 12
  CHECKPOINT_PERIOD: 100
TEST:
  IMS_PER_BATCH: 8


# local debug command: CUDA_VISIBLE_DEVICES=0 python tools/finetune.py --config-file configs/harold/dyhead_grounding.yaml --ft-tasks configs/odinw/_flickr.yaml --skip-train SOLVER.IMS_PER_BATCH 1 MODEL.WEIGHT OUTPUT/model_0345000.pth  OUTPUT_DIR tmp  TEST.IMS_PER_BATCH 1  TEST.EVAL_TASK grounding TEST.MDETR_STYLE_AGGREGATE_CLASS_NUM 100