DATALOADER:
  ASPECT_RATIO_GROUPING: false
  SIZE_DIVISIBILITY: 32

DATASETS:
  GENERAL_COPY: 16
  CAPTION_PROMPT: '[{"prefix": " ", "name": "fish", "suffix": ""}, {"prefix": "", "name": "jellyfish", "suffix": ""}, {"prefix": "", "name": "penguin", "suffix": " , which is black and white"}, {"prefix": "", "name": "puffin", "suffix": " with orange beaks "}, {"prefix": "", "name": "shark", "suffix": ""}, {"prefix": "", "name": "starfish", "suffix": ""}, {"prefix": "", "name": "stingray", "suffix": " which is flat and round"}, ]'
  REGISTER:
    test:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/test/annotations_without_background.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/test
    train:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train/annotations_without_background.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train
    val:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid/annotations_without_background.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid
  TEST: ("val",)
  TRAIN: ("train",)
INPUT:
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN: 800
MODEL:
  ATSS:
    NUM_CLASSES: 8
  DYHEAD:
    NUM_CLASSES: 8
  FCOS:
    NUM_CLASSES: 8
  ROI_BOX_HEAD:
    NUM_CLASSES: 8
SOLVER:
  CHECKPOINT_PERIOD: 100
  MAX_EPOCH: 12
  WARMUP_ITERS: 0
TEST:
  IMS_PER_BATCH: 8
