MODEL:
  ATSS:
    NUM_CLASSES: 8 # Placeholder
  FCOS:
    NUM_CLASSES: 8 # Placeholder
  ROI_BOX_HEAD:
    NUM_CLASSES: 8 # Placeholder
  DYHEAD:
    NUM_CLASSES: 8 # Placeholder
DATASETS:
  TRAIN: ("flickr30k_test", )
  TEST: ("flickr30k_test", )
  FLICKR_GT_TYPE: "separate"

INPUT:
  MIN_SIZE_TRAIN: 800
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
  ASPECT_RATIO_GROUPING: False